prints invalid option properly in several commands
* gadd, gick, giff, gtatus, and pick

diff --git a/gadd b/gadd
--- a/gadd
+++ b/gadd
@@ -2,10 +2,10 @@
 
 read -d '' helpDoc <<"helpDoc"
 NAME
-    gadd - add to git stage using gick
+    gadd - selects a file with gick to stage
 
 SYNOPSIS
-    gadd [-hNaD]
+    gadd [-hNaD] <substring>...
 
 DESCRIPTION
 TODO format description, very outdated
@@ -54,7 +54,7 @@ dryRun='false'
 
 
 # Options parsing
-while getopts hNswaD option; do
+while getopts :hNswaD option; do
 	case $option in
  		h)
 			# Print help
@@ -81,6 +81,7 @@ while getopts hNswaD option; do
 			dotCaseOptions+=' -$option'
 			;;
 		?)
+			echo "Invalid option: -$OPTARG" >&2
 			exit $error_invalidOptions
 			;;
 	esac
diff --git a/gick b/gick
--- a/gick
+++ b/gick
@@ -13,14 +13,14 @@ DESCRIPTION
 
 OPTIONS
     -h  Prints this help output.
-    
+
     -x  Prints also the status of the matched file. The format remains the
         same used by gtatus.
-    
+
     -s  Considers only files with any status in stage.
-    
+
     -w  Considers only files with any status in the workspace.
-    
+
     -a  Displays all files that match the search.
 helpDoc
 
@@ -38,7 +38,7 @@ pickOptions=''
 
 
 # Options parsing
-while getopts hxwsa option; do
+while getopts :hxwsa option; do
 	case $option in
  		h)
 			# Print help
@@ -63,6 +63,7 @@ while getopts hxwsa option; do
 			pickOptions+=" -$option"
 			;;
 		?)
+			echo "Invalid option: -$OPTARG" >&2
 			exit $error_invalidOptions
 			;;
 	esac
diff --git a/giff b/giff
--- a/giff
+++ b/giff
@@ -41,8 +41,7 @@ compareHeadAndStage='false'
 
 
 # Options parsing
-# TODO use here first the :options to print our own invalid option
-while getopts hiup option; do
+while getopts :hiup option; do
 	case $option in
  		h)
 			# Print help
@@ -66,6 +65,7 @@ while getopts hiup option; do
 			usePlainPath='true'
 			;;
 		?)
+			echo "Invalid option: -$OPTARG" >&2
 			exit $error_invalidOptions
 			;;
 	esac
diff --git a/gtatus b/gtatus
--- a/gtatus
+++ b/gtatus
@@ -10,13 +10,13 @@ SYNOPSIS
 DESCRIPTION
     Prints a sensible git status that can be consumed easily by other
     scripts.
-    
+
     The status printed is based in the output of `git status -z` and will
     comply with the following in the default settings:
      * The status of one file is ouput by line, with the usual format of
        one leter for stage status, one leter for workspace status, one
        space, and the filename.
-     * Filenames are not quoted regardless of the presence of spaces 
+     * Filenames are not quoted regardless of the presence of spaces
        within and no special characters are escaped.
      * No R status is ever printed, instead the status of both related
        files are printed each on its own line following the normal format.
@@ -24,11 +24,11 @@ DESCRIPTION
 
 OPTIONS
     -h  Prints this help output.
-    
+
     -c  Prints only the filenames, status are ommited.
-    
+
     -s  Prints only files with any status in stage.
-    
+
     -w  Prints only files with any status in the workspace.
 helpDoc
 
@@ -38,13 +38,14 @@ error_invalidOptions=1
 
 
 # Options values
+# TODO remove 'mode', its old style
 cutStatusMode='false'
 onlyStageStatus='false'
 onlyWorkspaceStatus='false'
 
 
 # Options parsing
-while getopts hcws option; do
+while getopts :hcws option; do
 	case $option in
  		h)
 			# Print help
@@ -68,6 +69,7 @@ while getopts hcws option; do
 			onlyWorkspaceStatus='true'
 			;;
 		?)
+			echo "Invalid option: -$OPTARG" >&2
 			exit $error_invalidOptions
 			;;
 	esac
@@ -109,33 +111,33 @@ for statusLine in $rawStatus; do
 		statusLine=$(git status -z -- "$fileName" | xargs -0 -n1 | head -n 1)
 		nextIsRenamedFile='false'
 	fi
-	
+
 	# Retrieve both status of the file
 	stageStatus=${statusLine:0:1}
 	workspaceStatus=${statusLine:1:1}
 	fileName=${statusLine:3}
-	
+
 	# Handing special R status
 	if [[ $stageStatus = 'R' ]]; then
 		# R status is for renamed files, its a mess, and it means the next
 		# line will contain ONLY the name of the file that was removed
 		nextIsRenamedFile='true'
-		
+
 		# Current file needs to be requested again to get its correct status
 		statusLine=$(git status -z -- "$relativePath$fileName")
 		stageStatus=${statusLine:0:1}
 		workspaceStatus=${statusLine:1:1}
 		fileName=${statusLine:3}
 	fi
-	
+
 	if [[ $onlyStageStatus = 'true' && $stageStatus = ' ' ]]; then
 		continue
 	fi
-	
+
 	if [[ $onlyWorkspaceStatus = 'true' && $workspaceStatus = ' ' ]]; then
 		continue
 	fi
-	
+
 	if [[ $cutStatusMode = 'true' ]]; then
 		echo "$relativePath$fileName"
 	else
diff --git a/pick b/pick
--- a/pick
+++ b/pick
@@ -10,21 +10,21 @@ SYNOPSIS
 DESCRIPTION
     Prints, from the content read from the standard input, the first line
     that contains in order all given <substring>s.
-    
+
     E.g,
-    
+
         # Having a file that contains a list of fruits
         > cat fruits
         blood orange
         green apple
         tangerine
-        
+
         > cat fruits | pick rang
         blood orange
-        
+
         > cat fruits | pick reen ple
         green apple
-        
+
         > cat fruits | pick rine tang
         # Output to stderr
         No match found
@@ -33,32 +33,32 @@ DESCRIPTION
     which can be output with the `-D` option. This allows the use of
     regular expresion terms in the <substring>s to furter refine the
     search.
-    
+
     E.g,
-        
+
         > cat fruits | pick g e
         blood orange
-        
+
         > cat fruits | pick ^g e
         green apple
-    
-    
+
+
     By default if all <substring>s contain only lowercase letters the
     matching is done ignoring all case diferences. If any upper case is
     used in the <substring>s the command will automatically switch to
     consider cases. This behaviour can be overriden with the -c option,
     which will force the command to always consider cases.
-    
+
     If no arguments or no content is piped in, or if no matching line is
     found, the script will exit with a non zero value.
 
 OPTIONS
     -h  Prints this help output.
-    
+
     -a  Displays all lines that match the search.
-    
+
     -c  Forces the command to consider case differences.
-    
+
     -D  Prints the regular expression used to search for matches.
 helpDoc
 
@@ -77,7 +77,7 @@ debugSearch='false'
 
 
 # Options parsing
-while getopts hacdD option; do
+while getopts :hacdD option; do
 	case $option in
  		h)
 			# Print help
@@ -101,6 +101,7 @@ while getopts hacdD option; do
 			debugSearch='true'
 			;;
 		?)
+            echo "Invalid option: -$OPTARG" >&2
 			exit $error_invalidOptions
 			;;
 	esac
