Minor renames in gush and gickb.

diff --git a/gickb b/gickb
--- a/gickb
+++ b/gickb
@@ -6,20 +6,20 @@
 # provided, it prints the first matching branch on remote branches. 
 
 params=`getopt r $*`
-paramsCode=$?
+getoptStatus=$?
 set -- $params
 
-if [[ $paramsCode != 0 ]]; then
-	echo 'Incorrect parameters given' >&2
+if [[ $getoptStatus != 0 ]]; then
+	echo 'Invalid options' >&2
 	exit 1
 fi
 
-useRemotes=false
+useRemotes=''
 
 for param; do
 	case "$param" in
 		-r)
-			useRemotes=true
+			useRemotes='-r'
 			shift;;
 		--)
 			shift; break;;
@@ -31,12 +31,5 @@ if [[ $# = 0 ]]; then
 	exit 2
 fi
 
-if [[ $useRemotes = true ]]; then
-	branches=`git branch -r`
-else
-	branches=`git branch`
-fi
-
-# There are three empty characters at the start of each line
-echo "$branches" | cut -c 3- | pick $@
+git branch $useRemotes | tr -d [:blank:] | tr -d '*' | pick $@
 
diff --git a/gush b/gush
--- a/gush
+++ b/gush
@@ -23,20 +23,20 @@
 
 
 # Error codes
-error_incorrectParams=1
+error_invalidOptions=1
 error_notInBranch=2
 error_noSingleRemote=3
 error_noRemoteMatch=4
 error_remoteBranchExists=5
 
-# Option parsing
+# Options parsing
 params=$(getopt d $*)
 getoptStatus=$?
 set -- $params
 
 if [[ $getoptStatus != 0 ]]; then
-	echo 'Incorrect parameters given' >&2
-	exit $error_incorrectParams
+	echo 'Invalid options' >&2
+	exit $error_invalidOptions
 fi
 
 dryrun=false
