Adding the -a option in pick to display all matches.

diff --git a/pick b/pick
--- a/pick
+++ b/pick
@@ -7,12 +7,15 @@
 # with a non-zero value. Samewise if no match is found in the content
 # piped in.
 
+
+# Error codes
 error_noStdin=1
 error_noParams=2
-error_invalidParams=3
-error_noMatch=4
+error_invalidOptions=3
+error_invalidParams=4
+error_noMatch=5
 
-
+# Basic checks
 if [[ -t 0 ]]; then
 	echo 'No stdin given' >&2
 	exit $error_noStdin
@@ -23,19 +26,30 @@ if [[ $# = 0 ]]; then
 	exit $error_noParams
 fi
 
-# TODO -a option will print all found matches
+# Options parsing
 params=`getopt a $*`
 getoptStatus=$?
-
 set -- $params
 
-# Shifting out the "--" that gets placed always at the start
-shift
-
-if [[ $getoptStatus != 0 ]];then
-	echo 'Invalid parameters' >&2
-	exit $error_invalidParams
+if [[ $getoptStatus != 0 ]]; then
+	echo 'Invalid options' >&2
+	exit $error_invalidOptions
 fi
+
+maxCount='--max-count 1'
+
+for param; do
+	case "$param" in
+		-a)
+			maxCount=''
+			shift
+			;;
+		--)
+			shift
+			break
+			;;
+	esac
+done
 
 piped=`cat`
 
@@ -50,7 +64,7 @@ done
 search=${search%"$wildCard"}
 
 # Piped needs to be between quotes as to not loose the newlines
-match=`echo "$piped" | grep --max-count 1 $search`
+match=`echo "$piped" | grep $maxCount $search`
 
 if [[ $? != 0 ]]; then
 	echo 'No match found' >&2
